<options>
	<auto_train> true </auto_train>
	<trials_per_experiment> 3 </trials_per_experiment>
</options>

<autotest> 
	<test_single_inputs> true </test_single_inputs>
	<test_combination_inputs> true </test_combination_inputs>
	<test_activation_functions> true </test_activation_functions>
</autotest>

# H1, H2, H3, TopoTraining, Activation, Max Epoc, Delta, Delta Window, Year, Month, Day, H Temp, A Temp, L Temp, H Humidity, A Humidity, L Humidity, H DP, A DP, L DP, Prec, H Press, A Press, L Press, H Vis, A Vis, L Vis, Fog, Rain, Snow, TS, H Wind, A Wind, G Wind, Pop, LOA, Lat, Long
<experiments>
,,,,,100,,0,1,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
8,8,8,true,,100,,0,1,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
8,8,8,false,,100,,0,1,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
8,8,,true,,100,,0,1,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
8,8,,false,,100,,0,1,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
8,,,true,,100,,0,1,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
8,,,false,,100,,0,1,0,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
</experiments>

<input_files>
	Outage Data/Final Sets/10_Hammond.csv
	Outage Data/Final Sets/100_Monticello.csv
	Outage Data/Final Sets/110_Goshen.csv
	Outage Data/Final Sets/150_Gary.csv
	Outage Data/Final Sets/160_Laporte.csv
	Outage Data/Final Sets/30_Crown Point.csv
	Outage Data/Final Sets/50_Valparaiso.csv
	Outage Data/Final Sets/70_Plymouth.csv
	Outage Data/Final Sets/90_Angola.csv
	Outage Data/Final Sets/ECE570_Final_Dataset.csv
</input_files>
